import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // middleware에서 설정한 nonce 값 가져오기
  const headersList = headers();
  const nonce = headersList.get("x-nonce") || "";

  return (
    <html lang="en">
      <head>
        {/* CSP nonce를 메타 태그로 추가 */}
        <meta name="csp-nonce" content={nonce} />
      </head>
      <script
        src="https://accounts.google.com/gsi/client"
        async
        defer
        nonce={nonce}
      ></script>
      <script
        async
        defer
        crossOrigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js"
      ></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
